### ISSUE TITLE
brix-demo jetty servlet problem - NoSuchMethodError - HttpServletRequest.isAsyncStarted

### ISSUE THREAD

**Issue by MarcGiffing** [brix-cms/brix-cms#201]
I've downloaded the current master and got the following exception if I call the index page in the browser. I seems that there is a version problem of the servlet spec. I've tried to fix it by myself but I've no clue whats wrong.

`[ERROR] Error for /brixdemo/index.html 
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z 	at org.apache.wicket.protocol.http.servlet.ServletWebResponse.flush(ServletWebResponse.java:309) 	at org.apache.wicket.protocol.http.HeaderBufferingWebResponse.flush(HeaderBufferingWebResponse.java:99) 	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:264) 	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:204) 	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:286) 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450) 	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230) 	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114) 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) 	at org.mortbay.jetty.Server.handle(Server.java:326) 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928) 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)`

**Comment by MarcGiffing** [comment]
OK, I've found the problem. The old maven jetty plugin is used which doesn't support the current servlet spec.

Current:
```
<groupId>org.mortbay.jetty</groupId>
<artifactId>maven-jetty-plugin</artifactId>
```

New:
```
<groupId>org.eclipse.jetty</groupId>
<artifactId>jetty-maven-plugin</artifactId>

<jetty.version>9.4.2.v20170220</jetty.version>
```

After migrating to the current version the problem is gone and I can access the page and admin section.
